"""Keep the Task "Assign" tab and frappe's real assignment (ToDo / _assign) in step.

WHY THIS EXISTS
---------------
frappe's "Add to ToDo" dialog (frappe/public/js/frappe/form/assign_to.js) is not a
set of Task fields: it inserts a **ToDo** row, and ToDo.on_update writes the hidden
`_assign` JSON on the Task. So the dialog's fields cannot simply be moved onto a tab.

They also cannot be made mandatory in their native form. The dialog needs a SAVED
document to attach a ToDo to, so "a Task cannot be saved without an assignee" plus
"a Task must be saved before it can be assigned" is a deadlock on every new Task.

The Assign tab is therefore real Custom Fields on Task (see mercury fixtures
custom_field.json). `custom_assign_to` is reqd, which works because it is an
ordinary field and is available before the first save. This module is what turns
that stored value into an actual assignment, so the sidebar "Assign", the
assignee's ToDo list, notifications and document sharing all behave exactly as
they do for the native dialog.

DIRECTION
---------
One way: tab field -> assignment. Assigning through the native sidebar dialog does
NOT write back into `custom_assign_to`. That is deliberate - a reverse sync would
have to guess which of several `_assign` users is "the" assignee, and the field is
mandatory anyway, so it always holds a value.
"""

import frappe
from frappe import _
from frappe.desk.form.assign_to import _add as assign_to_add
from frappe.desk.form.assign_to import remove as assign_to_remove

ASSIGN_FIELD = "custom_assign_to"


def validate_assignee(doc, method=None):
	"""An assignee is required on a real Task, but NOT on a template.

	A template Task is a blueprint - it is copied to create real tasks and is never
	worked on - so there is nobody to assign it to.

	The Custom Field carries mandatory_depends_on = "eval:!doc.is_template", which
	is what makes the form show the field as required only when it applies. That
	flag is NOT ENOUGH ON ITS OWN: frappe evaluates mandatory_depends_on only in
	JS (frappe/public/js/frappe/form/save.js and form/layout.js) - grep the python
	side and you will find it nowhere. So REST, Data Import, db.set_value and any
	server-side insert bypass it completely. This hook is the real control; the
	field flag is the UI half. Same split as the Delivered status gate in
	task_status.py - do not delete either as redundant.
	"""
	if doc.get("is_template"):
		return

	# Tasks generated by a Project Template cannot supply an assignee.
	#
	# Saving a Project with "From Template" set runs Project.copy_from_template()
	# -> create_task_from_template() (erpnext project.py:128-144), which inserts a
	# Task per template row. It copies subject, dates, weight, priority and so on
	# but NOT an assignee - the source is a template Task, which this very function
	# exempts, so there is nobody to copy. Throwing here aborted every task insert
	# and left the Project saved with zero tasks.
	#
	# So instead of blocking, inherit an owner: the Project's owner, falling back to
	# whoever is saving. That keeps the rule intact ("every real Task has an owner")
	# without making Project templates unusable, and on_update then creates the real
	# ToDo exactly as for a hand-assigned Task. The value is a sensible default, not
	# a guess about intent - reassign from the Assign tab like any other Task.
	#
	# `template_task` is set ONLY by that flow (project.py:142), so hand-made Tasks
	# are unaffected and still require an explicit assignee.
	if not doc.get(ASSIGN_FIELD) and doc.get("template_task"):
		inherited = None
		if doc.get("project"):
			inherited = frappe.db.get_value("Project", doc.project, "owner")
		doc.set(ASSIGN_FIELD, inherited or frappe.session.user)
		return

	if not doc.get(ASSIGN_FIELD):
		frappe.throw(
			_("{0} is required. Tick {1} if this Task is a blueprint rather than real work.").format(
				frappe.bold(_("Assign To")), frappe.bold(_("Is Template"))
			),
			frappe.MandatoryError,
			title=_("Assignee Required"),
		)


def sync_assignment(doc, method=None):
	"""Mirror the Assign tab onto a real ToDo assignment. Hooked on Task.on_update.

	on_update (not validate) because a ToDo needs doc.name, which does not exist
	until after the insert.
	"""
	user = doc.get(ASSIGN_FIELD)
	if not user:
		# reqd=1 normally prevents this; a fixture import or a bulk update with
		# ignore_mandatory can still get here. Nothing to mirror - leave any
		# existing assignment alone rather than silently clearing someone's ToDo.
		return

	current = frappe.parse_json(doc.get("_assign") or "[]") or []
	if user in current:
		return

	# Drop assignments this field previously created, so changing the assignee
	# moves the ToDo instead of accumulating one per edit. Closing another user's
	# ToDo is the intended behaviour: the tab field is the single source of truth
	# for who owns the Task.
	for previous in current:
		try:
			assign_to_remove(doc.doctype, doc.name, previous)
		except Exception:
			# A ToDo already closed/deleted by hand must not block the save.
			frappe.log_error(
				title="Mercury: could not clear previous Task assignment",
				message=frappe.get_traceback(),
			)

	assign_to_add(
		{
			"doctype": doc.doctype,
			"name": doc.name,
			"assign_to": [user],
			"description": doc.get("custom_assign_comment") or f"Assignment for Task {doc.name}",
			"date": doc.get("custom_assign_complete_by"),
			"priority": doc.get("custom_assign_priority") or "Medium",
		},
		# The assigner is editing the Task, so they already passed its write
		# permission check; re-running it here fails for roles that can edit a
		# Task but lack explicit read on the assignee's User record.
		ignore_permissions=True,
	)
